# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d2d14b72c4a7202553688dc741754af4"
name = "product-recommendation"
handle = "product-recommendation-48"
application_url = "https://worst-fields-viewed-tokyo.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://worst-fields-viewed-tokyo.trycloudflare.com/auth/callback",
  "https://worst-fields-viewed-tokyo.trycloudflare.com/auth/shopify/callback",
  "https://worst-fields-viewed-tokyo.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false

[build]
dev_store_url = "babyorgano-test.myshopify.com"
automatically_update_urls_on_dev = true
